server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置Nacos地址(Win)
        #server-addr: 192.168.203.140:1111 # 配置Nacos地址(Linux)

management:
  endpoints:
    web:
      exposure:
        include: '*'
